server:
  port: 8080
spring:
  application:
    name: "nequitest"
  devtools:
    add-properties: false
  main:
    lazy-initiation: false
logging:
  level:
    root: "INFO"
management:
  endpoints:
    web:
      exposure:
        include: "health"
      base-path: /actuator
    endpoint:
      health:
        show-details: always